version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pg"
      PGADMIN_DEFAULT_PASSWORD: "pg"
      PGADMIN_CONFIG_SERVER_MODE: "False"

    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80/tcp"
    restart: unless-stopped



volumes:
  db-data:
  pgadmin-data: